name: bcos-crypto GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]

jobs:
  build_with_clang:
    name: build_with_clang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install ccache
      - name: install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: sudo apt install -y git curl build-essential clang cmake
      - name: vcpkg essentials
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          export VCPKG_ROOT=$(pwd)/vcpkg
          export PATH=$PATH:$VCPKG_ROOT
      - name: configure
        if: runner.os == 'macOS'
        run: |
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path) && CC=/usr/bin/clang CXX=/usr/bin/clang++
          cmake --preset=test
      - name: configure
        if: runner.os == 'Linux'
        run: |
          export CC=/usr/bin/clang CXX=/usr/bin/clang++
          cmake --preset=test
      - name: compile
        run: cmake --build build -j2
      - name: run test
        run: cd build/bandersnatch && ctest